### PR TITLE
Changed Kotlin base app to Java base

### LINKED ISSUE #1: We should use Java instead of Kotlin
Currently the whole Android app is in Kotlin. Too many things to learn.

### PR DESCRIPTION
**Pull request by Eric1015**
closes #1

### CODE REVIEW

**Comment by Annnnnieee** [comment]
Damn! What a quick pr! 
Do you mind also adding a few things to git ignore? I forgot to do that the first time around. you can use something like this if you're not sure what to put in there: https://medium.com/@kunalsagar/perfect-gitignore-for-android-studio-projects-5518b06bda09

It's just to make sure we're not submitting environment related files, like ide configurations.

**Comment by Eric1015** [comment]
@Annnnnieee 
I've pushed a new change with that applied.

**Comment by Annnnnieee** [comment]
yeah, ok I see it. thanks!

**Comment by Eric1015** [comment]
Wait a sec!
It turns out that the github is actually denying me from pushing to this branch, so don't merge this branch for now.

**Comment by Eric1015** [comment]
# Update 
I was still not able to push my new change to this branch, so I will just merge this branch now and submit the new change in a separate branch.

**Pull request merged**
